# Generated by Django 4.1.3 on 2022-11-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='title',
            field=models.CharField(default='dupa', max_length=128),
            preserve_default=False,
        ),
    ]
