# Generated by Django 4.1.3 on 2022-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advert_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
