# Generated by Django 4.1.3 on 2022-11-19 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisements.image'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisements.image'),
        ),
    ]
