# Generated by Django 4.1.3 on 2022-11-19 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0007_alter_advert_category_alter_advert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.category'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='advertisements.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='advertisements.image'),
            preserve_default=False,
        ),
    ]
